[package]
name = "compact_jwt"
version = "0.1.2"
edition = "2018"
authors = ["William Brown <william@blackhats.net.au>"]
description = "Minimal implementation of JWT for OIDC"
repository = "https://github.com/kanidm/compact_jwt"
readme = "README.md"
keywords = ["jwt", "authentication"]
categories = ["authentication", "web-programming"]
license = "MPL-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13"
openssl = "0.10"
url = { version = "2", features = ["serde"] }
uuid = { version = "0.8", features = ["serde"] }
