[package]
name = "compact_jwt"
version = "0.2.0"
edition = "2021"
authors = ["William Brown <william@blackhats.net.au>"]
description = "Minimal implementation of JWT for OIDC"
repository = "https://github.com/kanidm/compact_jwt"
readme = "README.md"
keywords = ["jwt", "authentication"]
categories = ["authentication", "web-programming"]
license = "MPL-2.0"

[dependencies]
serde = { version = "^1.0.136", features = ["derive"] }
serde_json = "^1.0.79"
base64 = "^0.13.0"
openssl = "^0.10.38"
url = { version = "^2.2.2", features = ["serde"] }
uuid = { version = "^1.0.0", features = ["serde"] }
tracing = "^0.1.34"

[dev-dependencies]
tracing-subscriber = "^0.3.11"
